//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examination_work_Library
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities1 : DbContext
    {
        public LibraryEntities1()
            : base("name=LibraryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Discounted_books> Discounted_books { get; set; }
        public virtual DbSet<New_books> New_books { get; set; }
        public virtual DbSet<Popular_authors> Popular_authors { get; set; }
        public virtual DbSet<Popular_books> Popular_books { get; set; }
        public virtual DbSet<Popular_jenre> Popular_jenre { get; set; }
        public virtual DbSet<Reserved_books> Reserved_books { get; set; }
        public virtual DbSet<Sold_books> Sold_books { get; set; }
        public virtual DbSet<Written_off_books> Written_off_books { get; set; }
    }
}
